version: '3'
services:
  my-vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    container_name: my-portfolio-app-frontend
    volumes:
      - .:/app
    networks:
      - my-network

networks:
      my-network:
        external: true